### PR TITLE
Add Objects::nonNull filter to event listener

### PR DESCRIPTION
**Pull request by Scarsz**
Prevents possible NPEs

### CODE REVIEW

**Comment by Shengaero** [comment]
Could you please point out where exactly `null` might be added to the list?

@Scarsz

**Comment by Shengaero** [comment]
I am going to be blunt here.

You added half a line of code in less than a minute from when you created the fork that quite **literally does nothing**.

If you intend to PR to this project again, I would strongly advise you do so in a respectable fashion, as opposed to literally contributing dead code my IDE would tell me is not necessary.

**Comment by Scarsz** [comment]
I appreciate the feedback but I'd love if you weren't such a prude about it.

Now, your concerns:
1. Yes, the edit was made less than half a minute from when the fork was created. Do you even understand what the "edit" button on GitHub Web does? It allows you to fork, edit the file, and make a pull request all in two steps. The commit wasn't made from an IDE though it was tested inside of it.
2. The code doesn't "quite literally do nothing." Without it, I had NPEs relating directly to having null objects in the list, causing the entire thing to fail. Looking into it, the list had null objects inside of it. How? Don't know, don't care. Added the extra filter to skip null objects and lo and behold there's no more NPE and the code works correctly.
3. Not sure if you're familiar with the meaning of `dead code` but the filter is definitely preventing a NPE from occurring. It's not dead at all.

Thanks.

**Comment by jagrosh** [comment]
If you want to PR this, I'd recommend finding the source of the nulls and preventing them there, since there should never be nulls in this list.

**Comment by Scarsz** [comment]
How the nulls originate shouldn't matter. It's a safeguard filter that adds literally *nanoseconds* to the processing time of the statement. The fact that they were there in any environment at all where they weren't directly added by the user should be more than enough reason for that filter to be there.

**Comment by jagrosh** [comment]
Erm, it does matter... if nulls are getting into the list, it means there is a flaw somewhere earlier in the logic, and those nulls could propagate into other issues in other parts of the code or in future additions. No band-aid fixes please 😛

**Comment by Scarsz** [comment]
I won't be looking for the source of the nulls/doing a PR for it. Here's my easy fix that adds a nearly immeasurable overhead that would prevent other developers from having a similar issue. Will be using my own version of this file for now.

**Comment by kantenkugel** [comment]
@Scarsz looking at the code that adds elements to that list (single add statement)

https://github.com/JDA-Applications/JDA-Utilities/blob/6a5bc1014e4f05a22d6d89806a9269d9cab86cdb/src/main/java/com/jagrosh/jdautilities/waiter/EventWaiter.java#L115-L116

you can clearly see that the elements in the list are never null unless you do some bad code via reflection. 

My guess is that you provided a `null` predicate or consumer to the `waitForEvent` method which
- is not correctly checked by your null check because its not the list entry itself being null, but one of its properties
- is better fixed by not allowing those values at all to `waitForEvent` (throwing an `IllegalArgumentException`)
- while being a lib "bug" for allowing you to do so is also your fault for actually providing bad parameters

Edit: Your code doesn't even compile (forgot to import `Objects`). I guess you just made this edit without ever testing it (not even tested if it fixes your `NPE`)

**Comment by Shengaero** [comment]
To follow up on what @kantenkugel said, you're PR is not acceptable for more than just "me being a prude" (which is untrue). You failed to follow any sort of professionalism when making the PR, you did it in 30 seconds, as @jagrosh said, it was a bandaid fix, and I wouldn't be surprised if this was made inside the GitHub file editor (in fact I refuse to believe it wasn't made in the GitHub editor, it was made that fast and sloppily).

I personally find it very disrespectful that you would make such a small commit in such a small amount of time. You were denied because the PR **added nothing**. Not because I "was being prude". You could have come to the new #jda-utilities channel on the JDA Guild to ask us about whether or not this was even a valid issue! I would have been more than happy to talk it over with you! You wouldn't make this kind of PR to the actual JDA library, you shouldn't make it to JDA-Utilities!

Finally I am happy you will be using your own version of this file for now on!
Just make sure you are following the guidelines of the license, and provide the license-holder (being @jagrosh) credit for the original code!

**Comment by Shengaero** [comment]
On the basis of principle, I humored the intentions of this PR and actually made EventWaiter 110% null-safe [here](https://github.com/JDA-Applications/JDA-Utilities/commit/24d9c3cd6c84a549f563f33237978ce9f1749220).

**Pull request closed without merging**
