### PR TITLE
Correcting typo in OrderedMenu.Builder

### PR DESCRIPTION
**Pull request by Andre601**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing
[pull-request]: https://github.com/JDA-Applications/JDA-Utilities/pulls

#### Pull Request Checklist
Please follow the following steps before opening this PR.<br>
PRs that do not complete the checklist will be subject to denial for
missing information.

- [x] I have checked the [pull request page][pull-request] for upcoming
      or merged features/bug fixes.
- [x] I have read JDA's [contributing guidelines][contributing].

#### Pull Request Information
Check and fill in the blanks for all that apply:

- [x] My PR fixes a bug, error, or other issue with the library's codebase.
- [x] My PR is for the `menu` module of the JDA-Utilities library.
- [ ] My PR creates a new module for the JDA-Utilities library: `______`.

#### Description

This is a small PR that corrects a small description error in `useNumbers()` which gives `(A, B, C, etc.)` as example instead of `(1, 2, 3, etc,)`

### CODE REVIEW

**Comment by Sanduhr32** [comment]
> * [x]  My PR is for the `OrderedMenu.Builder` module of the JDA-Utilities library.

Did you mean `menu` module?

**Comment by Andre601** [comment]
> Did you mean menu module?

Most likely. I probably missmached there something. I mean the `OrderedMenu.jar` with this. But that is probably not the actual module.

**Comment by Sanduhr32** [comment]
You mean the menu module. What you mentioned is a class file of that module.

**Comment by Andre601** [comment]
Yeah. I corrected it in the message. 
Thanks for pointing that out ;)

**Pull request merged**
