### PR TITLE
Add TableBuilder utility class 

### PR DESCRIPTION
**Pull request by JohnnyJayJay**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing
[pull-request]: https://github.com/JDA-Applications/JDA-Utilities/pulls

#### Pull Request Checklist
Please follow the following steps before opening this PR.<br>
PRs that do not complete the checklist will be subject to denial for
missing information.

- [x] I have checked the [pull request page][pull-request] for upcoming
      or merged features/bug fixes.
- [x] I have read JDA's [contributing guidelines][contributing].

#### Pull Request Information
Check and fill in the blanks for all that apply:

- [ ] My PR fixes a bug, error, or other issue with the library's codebase.
- [x] My PR is for the `commons` module of the JDA-Utilities library.
- [ ] My PR creates a new module for the JDA-Utilities library: `______`.

#### Description

This adds a new class to the `utils`-package, `TableBuilder`. It can be used to create String tables, which is a nice feature for Discord codeblocks for example. 
You can configure the table individually and change each character used to display it. 

The class itself only makes use of the `Checks` util from JDA and `java.util.Arrays`.

### CODE REVIEW

**Comment by jagrosh** [comment]
A few things I'd like to see this support:
* More configuration of the framing characters, such that [box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) could be used (which have special cases for intersections)
* Similar to headers, row names (optional)
* Option to left justify/center/right justify

```
╔══════════╦══════════╦══════════╗
║  Table   ║ Header 1 ║ Header 2 ║
╠══════════╬══════════╬══════════╣
║  Row A   ║  Item 1  ║  Item 2  ║
╠══════════╬══════════╬══════════╣
║  Row B   ║  Item 3  ║  Item 4  ║
╚══════════╩══════════╩══════════╝
```

Another concern is that I'm not certain that the commons module (and utils package) is the right place for this. Down the road I could imagine support for several types of formatting helpers (graphs, times, music playback, etc), so it might be worth creating a new module to house these (this is my first impression anyway).

**Comment by JohnnyJayJay** [comment]
Thanks for your suggestions, I will definitely try to implement them.
I'm not sure about the module thing. I mean, it sounds reasonable, but I fear that in the end there is only one class in that module.

**Comment by jagrosh** [comment]
The module issue is a design choice that will need to be discussed with some of the other collaborators; you don't need to worry about that at the moment.

**Comment by JohnnyJayJay** [comment]
I added your suggested features 👍 
This really improved it a lot.

**Comment by JohnnyJayJay** [comment]
So, now there is more support for these box drawing characters. You can now customise basically any character. The defaults are now box drawing characters, too.
Executing the following code:
```java
String table = new TableBuilder().setHeaders("Header 1", "Header 2", "Header 3")
     .setName("Sample Name")
     .setValues(new String[][] {
           {"Item 1", "Item 2", "Item 3"},
           {"Item 4", "Item 5", "Item 6"},
           {"Item 7", "Item 8", "Item 9"}
      })
      .setRowNames("Row 1", "Row 2", "Row 3")
      .frame(true)
      .build();
System.out.println(table);
```
Results in this table:
```
┌───────────╥────────┬────────┬────────┐
│Sample Name║Header 1│Header 2│Header 3│
╞═══════════╬════════╪════════╪════════╡
│   Row 1   ║ Item 1 │ Item 2 │ Item 3 │
├───────────╫────────┼────────┼────────┤
│   Row 2   ║ Item 4 │ Item 5 │ Item 6 │
├───────────╫────────┼────────┼────────┤
│   Row 3   ║ Item 7 │ Item 8 │ Item 9 │
└───────────╨────────┴────────┴────────┘
```

**Comment by jagrosh** [comment]
I haven't tested this yet (I didn't have a chance to test when I was home yesterday), but one more thing that I'd like to see is a settable padding value (default 0) which is a number of spaces to be added to both sides of the widest item in each column when auto-adjust is used.

For example, your most recent example with padding of 1 would look like:
```
┌─────────────╥──────────┬──────────┬──────────┐
│ Sample Name ║ Header 1 │ Header 2 │ Header 3 │
╞═════════════╬══════════╪══════════╪══════════╡
│    Row 1    ║  Item 1  │  Item 2  │  Item 3  │
├─────────────╫──────────┼──────────┼──────────┤
│    Row 2    ║  Item 4  │  Item 5  │  Item 6  │
├─────────────╫──────────┼──────────┼──────────┤
│    Row 3    ║  Item 7  │  Item 8  │  Item 9  │
└─────────────╨──────────┴──────────┴──────────┘
```

**Comment by kantenkugel** [comment]
I would actually set padding to default to 1... as the 0 padding looks kinda bad

Also: do you HAVE to set the name + row names? I would prefer just giving it data and it only using those to display (often you don't have row-centered data like above)

EG using your example above (without row-based naming):

```java
String table = new TableBuilder().setHeaders("Header 1", "Header 2", "Header 3")
     .setValues(new String[][] {
           {"Item 1", "Item 2", "Item 3"},
           {"Item 4", "Item 5", "Item 6"},
           {"Item 7", "Item 8", "Item 9"}
      })
      .frame(true)
      .build();
System.out.println(table);
```
-->
```
┌──────────╥──────────┬──────────┐
│ Header 1 │ Header 2 │ Header 3 │
╞══════════╬══════════╪══════════╡
│  Item 1  │  Item 2  │  Item 3  │
├──────────╫──────────┼──────────┤
│  Item 4  │  Item 5  │  Item 6  │
├──────────╫──────────┼──────────┤
│  Item 7  │  Item 8  │  Item 9  │
└──────────╨──────────┴──────────┘
```

**Comment by JohnnyJayJay** [comment]
Row names + table name is optional. You can leave it out if you want :)

**Comment by kantenkugel** [comment]
After looking at the code i think it might benefit immensely from a few changes:

- Make the header optional too
- Use an enum for alignment. Thats exactly what they are there for
- Have an inner class that provides all the frame chars (with some default instances provided as statics). This allows to pick between some common ones + even if a user chooses to go with a custom one, he only has to create a single instance of that TableBorders class and pass that to every TableBuilder that is used instead of having to call 20 setX() methods providing all the chars every time the builder is used

**Comment by JohnnyJayJay** [comment]
Thanks for the suggestions. Especially the last one sounds reasonable considering that, after the additions, there are quite a few chars to set.
I was also thinking about using an enum, I don't know why I decided against it.
I will realise your ideas in the next few days.

**Pull request merged**
