### PR TITLE
Update Utils to work with JDA v4

### PR DESCRIPTION
**Pull request by kantenkugel**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing
[pull-request]: https://github.com/JDA-Applications/JDA-Utilities/pulls

#### Pull Request Checklist
Please follow the following steps before opening this PR.<br>
PRs that do not complete the checklist will be subject to denial for
missing information.

- [x] I have checked the [pull request page][pull-request] for upcoming
      or merged features/bug fixes.
- [x] I have read JDA's [contributing guidelines][contributing].

#### Pull Request Information
Check and fill in the blanks for all that apply:

- [x] My PR fixes a bug, error, or other issue with the library's codebase.
- [ ] My PR is for the `______` module of the JDA-Utilities library.
- [ ] My PR creates a new module for the JDA-Utilities library: `______`.

#### Description

Updating JDA-Utilities to work with JDA v4.
The only significant change that end users should see is that `CommandEvent#getGroup()` is no longer a thing

### CODE REVIEW

**Comment by Andre601** [comment]
Does this PR when merged fully support JDA v4 or would there be other PRs to add?

**Comment by kantenkugel** [comment]
@Andre601 im not entirely sure what you mean with that statement. If its about new features: No. I only migrated existing code to JDAv4, I didn't add new features to Utils (IMO not in the scope of this PR)

**Comment by Andre601** [comment]
I just asked if JDA-utilities will be fully V4 compatible with this PR, or if there will be some other changes before it is completely compatible... It really isn't that hard to understand.

**Comment by JohnnyJayJay** [comment]
What would be the point of this PR if it didn't make it compatible? It's literally in the title.

**Comment by Andre601** [comment]
It could still be the case that some other changes (Like updating the modules) would be done in different PRs.
There is no need to attack me like that. I asked a simple question to be sure.

**Comment by MCOfficer** [comment]
> 
> 
> It could still be the case that some other changes (Like updating the modules) would be done in different PRs.
> There is no need to attack me like that. I asked a simple question to be sure.

can we blame this on different interpretations of "compatible" and move on?

**Comment by JohnnyJayJay** [comment]
> > It could still be the case that some other changes (Like updating the modules) would be done in different PRs.
> > There is no need to attack me like that. I asked a simple question to be sure.
> 
> can we blame this on different interpretations of "compatible" and move on?

I still don't quite understand what this is about anyway. As far as I see it, this PR updates all of the affected modules.

**Comment by jagrosh** [comment]
I'll test this tonight; this will also merit a minor version bump

**Comment by DV8FromTheWorld** [comment]
Since it is moving to a new version of JDA, doesn't that make it effectively a breaking change?
I'd think that'd call for a major release version bump.

**Comment by MelanX** [comment]
I tested this a bit and it crashes if I use 
`CommandClient client = builder.build()` (like in the Example section)

**Comment by MCOfficer** [comment]
> 
> 
> I tested this a bit and it crashes if I use
> `CommandClient client = builder.build()` (like in the Example section)

Could you provide the error, please?

**Comment by MelanX** [comment]
`Exception in thread "main" java.lang.IllegalArgumentException: Owner ID was set null or not set! Please provide an User ID to register as the owner!`
I don't know which User ID
Without this line everything works fine (but no command is working)

**Comment by Andre601** [comment]
> `Exception in thread "main" java.lang.IllegalArgumentException: Owner ID was set null or not set! Please provide an User ID to register as the owner!`
> I don't know which User ID
> Without this line everything works fine (but no command is working)

https://github.com/jagrosh/ExampleBot/blob/ff95e4cfbde27b54ad91d02de3244ca2bee997c5/src/main/java/com/jagrosh/examplebot/ExampleBot.java#L55-L56

https://github.com/jagrosh/ExampleBot/blob/ff95e4cfbde27b54ad91d02de3244ca2bee997c5/src/main/java/com/jagrosh/examplebot/ExampleBot.java#L61-L62

I would recommend to check the linked example bot to prevent such issues in the future

**Comment by MinnDevelopment** [comment]
@jagrosh whats the status on this?

**Review by jagrosh — APPROVED** [review]
Just tested my example bot with this branch, everything I tested seemed to work

**Pull request merged**
